export const ADD_TODO ="ADD_TODO";
export const TOGGLE_TODO ="TOGGLE_TODO";
export const SHOW_ALL ="SHOW_ALL";
export const SHOW_ACTIVE ="SHOW_ACTIVE";
export const SHOW_COMPELET ="SHOW_COMPELET";
export const SET_VISIBILITY_ACTION ="SET_VISIBILITY_ACTION";